version: "3.7"  

services:
    logstash:
        container_name: logstash            
        image: docker.elastic.co/logstash/logstash:7.10.2
        hostname: logstash
        domainname: logstash
      
        environment:
#            - discovery.type=single-node
#            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms256m -Xmx256m" 
            
        command: logstash -f /usr/share/logstash/pipeline/logstash.conf
                    
        networks:
            - es-tier
            
#        ports:
#          - 5044:5044
#          - 5000:5000/tcp
#          - 5000:5000/udp
#          - 9600:9600           
          
        volumes:
          - /opt/docker/elasticsearch/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
          - /opt/docker/elasticsearch/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
          - /opt/docker/elasticsearch/logstash/numeraciongeografica.csv:/csv/numeraciongeografica.csv
                         
networks:
    es-tier:
        name: es-tier
        driver: bridge
  

   